AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  belajarpythonbot

  Sample SAM Template for belajarpythonbot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  BPBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: belajarpythonbot2023
      Events:
        BPBot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /belajarpythonbot
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BPBotApi:
    Description: "API Gateway endpoint URL for Prod stage for BPBot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/belajarpythonbot/"
  BPBotFunction:
    Description: "BPBot Lambda Function ARN"
    Value: !GetAtt BPBotFunction.Arn
  BPBotFunctionIamRole:
    Description: "Implicit IAM Role created for BPBot function"
    Value: !GetAtt BPBotFunctionRole.Arn
